const dayjs = require("dayjs");

const HealthData = [
  {
    id: 1001,
    userId: 1,
    birthDate: dayjs(new Date(1995, 10, 1)),
    healthStatus: {
      family: ["พ่อแม่เป็นความดัน"],
      myself: ["-"],
    },
    exercise: [
      {
        date: dayjs(new Date(2021, 8)),
        weight: 76.1,
        height: 172,
        time: 34,
      },
      {
        date: dayjs(new Date(2021, 9)),
        weight: 72.2,
        height: 172,
        time: 32,
      },
      {
        date: dayjs(new Date(2021, 10)),
        weight: 70.4,
        height: 172,
        time: 40,
      },
      {
        date: dayjs(new Date(2021, 11)),
        weight: 67.4,
        height: 172,
        time: 29,
      },
      {
        date: dayjs(new Date(2021, 12)),
        weight: 64.1,
        height: 172,
        time: 33,
      },
    ],
    // rightUser = 1 is employee and 2 is family
    treatment: [
      {
        id: 1,
        category: 1,
        right: 1,
        section: "ทำแผลหกล้ม",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 1200,
        icon: "",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 1,
        section: "ผ่านตัดตับ",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 200000,
        icon: "",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 2,
        section: "-",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 2000,
        icon: "",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 3,
        section: "-",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 1000,
        icon: "",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 3,
        category: 2,
        right: 4,
        section: "-",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 10000,
        icon: "",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 4,
        category: 2,
        right: 5,
        section: "-",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 12000,
        icon: "",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 5,
        category: 3,
        right: 1,
        section: "ถอนฝันครุด",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 3000,
        icon: "",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 6,
        category: 1,
        right: 1,
        section: "ปวดหัวเป็นไข้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 1400,
        icon: "sick.svg",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 6,
        category: 2,
        right: 1,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 200000,
        icon: "surgery.svg",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 6,
        category: 2,
        right: 2,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 3000,
        icon: "surgery.svg",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 6,
        category: 2,
        right: 3,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 2000,
        icon: "surgery.svg",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 4,
        section: "บำบัดจิต",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 15000,
        icon: "sick.svg",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 8,
        category: 2,
        right: 5,
        section: "เสริมคาง",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 30000,
        icon: "surgery.svg",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 9,
        category: 3,
        right: 1,
        section: "ถอนฟัน",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 2500,
        icon: "surgery.svg",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 10,
        category: 1,
        right: 1,
        section: "ทำแผล",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 800,
        icon: "bandaged.svg",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
    ],
  },
];

module.exports = HealthData;
