const Item = [
  {
    id: 2001,
    name: "Iphone 12 pro",
    quantity: 20,
    detail:
      "A14 Bionic ที่แรงแซงหน้าชิพในบรรดาสมาร์ทโฟนอื่นๆ ไปไกลหลายขุม ระบบกล้องระดับโปรที่ยกระดับการถ่ายภาพใน สภาวะแสงน้อยไปอีกขั้น รวมทั้ง Ceramic Shield ที่ทนต่อการตกกระแทกได้ดีขึ้น 4 เท่า",
    category: 6,
    price: 8000,
    discount: 10,
    newPrice: 7200,
    brand: "Apple",
    skuCode: 2001001,
    warranty: 1,
    warrantyDetail: "รับประกันความผิดปกติของสินค้าที่เกิดจากการผลิต",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 20,
    image: [
      "/item/iphone12Pro_model.png",
      "/item/iphone12Pro_color.png",
      "/item/iphone12Pro_detail.png",
    ],
    type: "lifestyle",
    count: 500,
  },
  {
    id: 2002,
    name: "PlayStation Pro",
    quantity: 30,
    detail:
      "Sony PlayStation Pro ความจุ 2TB ตัวเครื่องแสดงผลภาพระดับ 4K/60 Fps รองรับระบบ HDR ให้ความคมชัดของภาพกราฟิก ให้นักเกมเมอร์ได้สัมผัสกับเกมได้สนุกยิ่งขึ้น",
    category: 3,
    price: 4000,
    discount: 5,
    newPrice: 3800,
    brand: "Sony",
    skuCode: 2001002,
    warranty: 1,
    warrantyDetail: "รับประกันความผิดปกติของสินค้าที่เกิดจากการผลิต",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 30,
    image: ["/item/ps5Box.png", "/item/ps5Model.png", "/item/ps5Joy.png"],
    type: "lifestyle",
    count: 1000,
    popular: true,
  },
  {
    id: 2003,
    name: "MacBook Air 13: M1",
    quantity: 30,
    detail:
      "MacBook Air พลังหนักๆ บนความบางเบา โน้ตบุ๊คที่บางและเบาที่สุดของเรา วันนี้พลิกโฉมใหม่หมดในทุกด้าน ด้วยชิพ Apple M1 ที่ทำให้มี CPU เร็วขึ้นสูงสุด 3.5 เท่า และ GPU เร็วขึ้นสูงสุด 5 เท่า รวมทั้ง Neural Engine ที่ล้ำหน้าที่สุดของเรา ซึ่งเสริมให้การเรียนรู้ของระบบเร็วขึ้นสูงสุดถึง 9 เท่า พร้อมด้วยแบตเตอรี่ที่ใช้งานได้นานที่สุดเท่าที่เคยมีมาใน MacBook Air ซึ่งครั้งนี้มาในดีไซน์แบบไม่มีพัดลมที่มีก็แต่ความเงียบ เอาเป็นว่า ไม่เคยมีครั้งไหนที่พลังระดับนี้จะพร้อมไปกับคุณได้เท่านี้มาก่อน",
    category: 1,
    price: 8500,
    discount: 0,
    newPrice: 8500,
    brand: "Apple",
    skuCode: 2001003,
    warranty: 1,
    warrantyDetail: "รับประกันความผิดปกติของสินค้าที่เกิดจากการผลิต",
    deliveryType: 1,
    deliveryTime: 5,
    deliveryCost: 50,
    image: ["/item/mba1.png", "/item/mba2.png", "/item/mba3.png"],
    type: "lifestyle",
    count: 1000,
    popular: true,
  },
  {
    id: 2004,
    name: "Galaxy Watch 4 44mm",
    quantity: 30,
    detail:
      "Galaxy Watch 4 นาฬิกาหน้าปัดกลม มาพร้อมระบบปฏิบัติการ Wear OS + One UI Watch มีความแม่นยำมากถึง 98% ใช้เวลาตรวจเช็คเพียง 15 วินาที (ฟังก์ชั่นการใช้งานการวัดความดันโลหิตและการตรวจสอบคลื่นไฟฟ้าหัวใจรออนุมัติจากทางสำนักงานองค์การอาหารและยา) แสดงข้อมูลการนอนได้ละเอียดมากยิ่งขึ้น พร้อมฟังก์ชันตรวจจับการกรนและแสดงออกซิเจนในกระแสเลือดขณะนอนหลับ และประมวลผลออกมาเป็นคะแนนการนอนหลับเพื่อความเข้าใจที่ง่ายขึ้น",
    category: 3,
    price: 3000,
    discount: 0,
    newPrice: 3000,
    brand: "Samsung",
    skuCode: 2001004,
    warranty: 2,
    warrantyDetail: "รับประกันความผิดปกติของสินค้าที่เกิดจากการผลิต",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 10,
    image: ["/item/ssw1.png", "/item/ssw2.png", "/item/ssw3.png"],
    type: "lifestyle",
    count: 1000,
    popular: false,
  },
  {
    id: 2005,
    name: "HERO9 Black",
    quantity: 30,
    detail:
      "กล้อง GoPro HERO9 มาพร้อมจอดิสเพลย์ด้านหน้า และคุณภาพวีดีโอที่สูงถึง 5K และภาพนิ่งความละเอียด 20 ล้านพิกเซล รองรับการใช้งานที่ยาวนานยิ่งขึ้นกว่าเดิมถึง 30% พร้อมระบบลดการสั่นไหวรุ่นใหม่ล่าสุดกับ HyperSmooth 3.0 และโหมดถ่ายวีดีโออัจฉริยะ TimeWarp 3.0 พร้อมฟังก์ชันภายในที่ฉลาดกว่าเดิมด้วย Power Tools และยังสามารถเปลี่ยนเป็นกล้อง Webcam ได้ และยังรองรับการใช้งานคำสั่งเสียงพร้อมกันน้ำทันที 10 เมตรโดยไม่ต้องใส่เคส",
    category: 4,
    price: 3500,
    discount: 0,
    newPrice: 3500,
    brand: "GoPro",
    skuCode: 2001005,
    warranty: 1,
    warrantyDetail: "รับประกันความผิดปกติของสินค้าที่เกิดจากการผลิต",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 10,
    image: ["/item/gh1.png", "/item/gh2.png", "/item/gh3.png"],
    type: "lifestyle",
    count: 1000,
    popular: false,
  },
  {
    id: 2006,
    name: "Mini Arcade FM1J2X1800",
    quantity: 30,
    detail:
      "NEOGEO mini ตำนานตู้เกม Arcade ชื่อดังจากค่าย SNK ที่กลับมาอีกครั้งในขนาดพาพา มาพร้อม 40 เกมระดับตำนานของ SNK ที่จะทำให้แฟนเกมยุค 90s' ได้รำลึกถึง เช่น The King of Fighters, Samurai Showdown, Metal Slug และอีกหลากหลายเกม ตัวเครื่องมีหน้าจอ LCD 3.5 นิ้วในตัว พร้อมคอนโทรลเลอร์สไตล์เกมตู้อาเขตสุดคลาสสิค ใช้พลังงานน้อยรับไฟจากช่อง USB Type C สามารถต่อกับทีวีหรือหน้าจอผ่านทางช่อง Mini HDMI และ ต่อจอยคอนโทรลเลอร์เสริมได้",
    category: 5,
    price: 1500,
    discount: 0,
    newPrice: 1500,
    brand: "Neogeo",
    skuCode: 2001006,
    warranty: 2,
    warrantyDetail: "รับประกันความผิดปกติของสินค้าที่เกิดจากการผลิต",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 5,
    image: ["/item/nn1.png", "/item/nn2.png", "/item/nn3.png"],
    type: "lifestyle",
    count: 1000,
    popular: true,
  },
];

module.exports = Item;
