const Payruns = [
  {
    id: 1,
    username: "admin",
    email: "admin@scg.com",
    password: "adminadmin",
    image: "1.jpg",
    firstname: "Tapmid",
    lastname: "Humphries",
    idDepartment: 13,
    department: "HR Business Partner",
    position: "Assistant Manager-HR Business Partner",
    mobileNumber: "065-556-3915",
    workingLocation: "Rayong Site#1",
    site: 1,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: [],
  },
  {
    id: 2,
    username: "manager",
    email: "manager@scg.com",
    password: "managermanager",
    image: "2.jpg",
    firstname: "Theodor",
    lastname: "O'Moore",
    idDepartment: 13,
    department: "HR Business Partner",
    position: "Manager-HR Business Partner",
    mobileNumber: "085-550-0949",
    workingLocation: "Rayong Site#1",
    site: 1,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 3,
    username: "user",
    email: "user@scg.com",
    image: "3.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-558-9673",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 4,
    username: "superuser",
    email: "mandeemc@domain.com",
    password: "superuser",
    image: "4.jpg",
    firstname: "Mandeep",
    lastname: "Mccray",
    idDepartment: 5,
    department: "Catalyst & Pilot Plant Production Department",
    position: "Catalyst Production Operator",
    mobileNumber: "095-557-3152",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 5,
    username: "vendor",
    email: "vendor@domain.com",
    password: "vendorvendor",
    image: "5.jpg",
    firstname: "Alayna",
    lastname: "Wolfe",
    idDepartment: 2,
    department: "Quality Assurance & Quality Control Department",
    position: "Quality Control Technician - PAL",
    mobileNumber: "085-558-4021",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 6,
    username: "anishava",
    email: "anishava@domain.com",
    image: "6.jpg",
    firstname: "Anisha",
    lastname: "Valdez",
    idDepartment: 12,
    department: "Safety, Occupational Health & Environment Department",
    position: "Occupational Health & Safety System Engineer",
    mobileNumber: "085-555-6279",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 7,
    username: "aedankn",
    email: "aedankn@domain.com",
    image: "7.jpg",
    firstname: "Aedan",
    lastname: "Knights",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "095-554-4538",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 8,
    username: "kaitlabr",
    email: "kaitlabr@domain.com",
    image: "8.jpg",
    firstname: "Kaitlan",
    lastname: "Braun",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-559-9269",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 9,
    username: "krystich",
    email: "krystich@domain.com",
    image: "9.jpg",
    firstname: "Krystian",
    lastname: "Chase",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-557-9798",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 10,
    username: "wilburro",
    email: "wilburro@domain.com",
    image: "10.jpg",
    firstname: "Wilbur",
    lastname: "Roberts",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-557-2907",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 11,
    username: "maciema",
    email: "maciema@domain.com",
    image: "11.jpg",
    firstname: "Macie",
    lastname: "Marshall",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "095-554-0195",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 12,
    username: "amiecr",
    email: "amiecr@domain.com",
    image: "12.jpg",
    firstname: "Amie",
    lastname: "Croft",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-556-3474",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 13,
    username: "keeganba",
    email: "keeganba@domain.com",
    image: "13.jpg",
    firstname: "Keegan",
    lastname: "Bates",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-555-0867",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 14,
    username: "roisinmi",
    email: "roisinmi@domain.com",
    image: "14.jpg",
    firstname: "Roisin",
    lastname: "Millington",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-555-7752",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 15,
    username: "elenibi",
    email: "elenibi@domain.com",
    image: "15.jpg",
    firstname: "Eleni",
    lastname: "Bishop",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-552-2903",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 16,
    username: "rajfr",
    email: "rajfr@domain.com",
    image: "16.jpg",
    firstname: "Raj",
    lastname: "Fraser",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-557-5467",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 17,
    username: "dottybo",
    email: "dottybo@domain.com",
    image: "17.jpg",
    firstname: "Dotty",
    lastname: "Bowers",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-553-1111",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 18,
    username: "saeedal",
    email: "saeedal@domain.com",
    image: "18.jpg",
    firstname: "Saeed",
    lastname: "Alvarado",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "095-555-7759",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 19,
    username: "gurleele",
    email: "gurleele@domain.com",
    image: "19.jpg",
    firstname: "Gurleen",
    lastname: "Leon",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-556-3139",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 20,
    username: "adrianca",
    email: "adrianca@domain.com",
    image: "20.jpg",
    firstname: "Adrianna",
    lastname: "Campos",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-552-3709",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 21,
    username: "enyapi",
    email: "enyapi@domain.com",
    image: "21.jpg",
    firstname: "Enya",
    lastname: "Pittman",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-558-6568",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 22,
    username: "keithva",
    email: "keithva@domain.com",
    image: "22.jpg",
    firstname: "Keith",
    lastname: "Vazquez",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-551-9891",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 23,
    username: "arjunco",
    email: "arjunco@domain.com",
    image: "23.jpg",
    firstname: "Arjun",
    lastname: "Connolly",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-559-8630",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 24,
    username: "michalki",
    email: "michalki@domain.com",
    image: "24.jpg",
    firstname: "Michalina",
    lastname: "King",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "095-550-3437",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 25,
    username: "mathilbo",
    email: "mathilbo@domain.com",
    image: "25.jpg",
    firstname: "Mathilda",
    lastname: "Bonilla",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "095-551-9585",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 26,
    username: "kerysrh",
    email: "kerysrh@domain.com",
    image: "26.jpg",
    firstname: "Kerys",
    lastname: "Rhodes",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-551-4975",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 27,
    username: "bartosse",
    email: "bartosse@domain.com",
    image: "27.jpg",
    firstname: "Bartosz",
    lastname: "Sexton",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-557-7282",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 28,
    username: "annmarkl",
    email: "annmarkl@domain.com",
    image: "28.jpg",
    firstname: "Ann-Marie",
    lastname: "Klein",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-553-2502",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 29,
    username: "kajolwh",
    email: "kajolwh@domain.com",
    image: "29.jpg",
    firstname: "Kajol",
    lastname: "Whittington",
    idDepartment: 2,
    department: "Quality Assurance & Quality Control Department",
    position: "Quality Assurance & Quality Control Department",
    mobileNumber: "085-558-0153",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
  {
    id: 30,
    username: "evelynst",
    email: "evelynst@domain.com",
    image: "30.jpg",
    firstname: "Evelyn",
    lastname: "Stevenson",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-551-7861",
    workingLocation: "Rayong Site#3",
    site: 3,
    company: "Thai Polyethylene Co., Ltd.",
    grossPay: 30000,
    estTaxes: 2222,
    addition:[],
    deduction:[],
    reimbursement:[],
    contribution: []
  },
];
module.exports = Payruns;
