const dayjs = require("dayjs");

const Review = [
  {
    id: 1,
    postId: 1,
    type: "insurance",
    message:
      "Car was higher mileage than expected and makes some noises along the way. Not super pleased about the tacky “rent me” license plate holder on the back of the car. Not what you would expect from a higher end rental like this.",
    posterId: 1,
    firstname: "Tapmid",
    lastname: "Humphries",
    image: "1.jpg",
    return: [
      {
        message: "thank you",
        posterId: 8,
        firstname: "Kaitlan",
        lastname: "Braun",
        image: "8.jpg",
        date: dayjs(new Date(2021, 10, 11, 9, 30)),
      },
    ],
    rating: 4.6,
    date: dayjs(new Date(2021, 10, 10, 10, 12)),
  },
  {
    id: 2,
    postId: 2,
    type: "insurance",
    message:
      "Tony was extremely helpful both in preparation and during my trip! Would definitely ride again!",
    posterId: 1,
    firstname: "Tapmid",
    lastname: "Humphries",
    image: "1.jpg",
    return: [],
    rating: 4,
    date: dayjs(new Date(2021, 10, 8, 8, 12)),
  },
  {
    id: 3,
    postId: 3,
    type: "insurance",
    message: "Loved this car. And Tony made the whole process a breeze!",
    posterId: 4,
    firstname: "Mandeep",
    lastname: "Mccray",
    image: "4.jpg",
    return: [],
    rating: 4.6,
    date: dayjs(new Date(2021, 9, 30, 10, 35)),
  },
  {
    id: 4,
    postId: 1,
    type: "package",
    message:
      "Tony is a great communicator and his car was very nice. The check in and check out process was a breeze and I felt very comfortable while using his car. Really great car.",
    posterId: 2,
    firstname: "Theodor",
    lastname: "O'Moore",
    image: "2.jpg",
    return: [
      {
        message: "thank you",
        posterId: 8,
        firstname: "Kaitlan",
        lastname: "Braun",
        image: "8.jpg",
        date: dayjs(new Date(2021, 10, 11, 9, 30)),
      },
    ],
    rating: 4.6,
    date: dayjs(new Date(2021, 10, 10, 10, 12)),
  },
  {
    id: 5,
    postId: 2,
    type: "package",
    message: "Great communication and very helpful",
    posterId: 3,
    firstname: "Shaunna",
    lastname: "Richard",
    image: "3.jpg",
    return: [],
    rating: 4,
    date: dayjs(new Date(2021, 10, 8, 8, 12)),
  },
  {
    id: 6,
    postId: 3,
    type: "package",
    message: "Loved this car. And Tony made the whole process a breeze!",
    posterId: 4,
    firstname: "Mandeep",
    lastname: "Mccray",
    image: "4.jpg",
    return: [],
    rating: 4.6,
    date: dayjs(new Date(2021, 9, 30, 10, 35)),
  },
  {
    id: 7,
    postId: 1,
    type: "lifestyle",
    message:
      "Tony is a great communicator and his car was very nice. The check in and check out process was a breeze and I felt very comfortable while using his car. Really great car.",
    posterId: 2,
    firstname: "Theodor",
    lastname: "O'Moore",
    image: "2.jpg",
    return: [
      {
        message: "thank you",
        posterId: 8,
        firstname: "Kaitlan",
        lastname: "Braun",
        image: "8.jpg",
        date: dayjs(new Date(2021, 10, 11, 9, 30)),
      },
    ],
    rating: 4.6,
    date: dayjs(new Date(2021, 10, 10, 10, 12)),
  },
  {
    id: 8,
    postId: 2,
    type: "lifestyle",
    message: "Great communication and very helpful",
    posterId: 3,
    firstname: "Shaunna",
    lastname: "Richard",
    image: "3.jpg",
    return: [],
    rating: 4,
    date: dayjs(new Date(2021, 10, 8, 8, 12)),
  },
  {
    id: 9,
    postId: 3,
    type: "lifestyle",
    message: "Loved this car. And Tony made the whole process a breeze!",
    posterId: 4,
    firstname: "Mandeep",
    lastname: "Mccray",
    image: "4.jpg",
    return: [],
    rating: 4.6,
    date: dayjs(new Date(2021, 9, 30, 10, 35)),
  },
  {
    id: 10,
    postId: 1,
    type: "travel",
    message:
      "Tony is a great communicator and his car was very nice. The check in and check out process was a breeze and I felt very comfortable while using his car. Really great car.",
    posterId: 2,
    firstname: "Theodor",
    lastname: "O'Moore",
    image: "2.jpg",
    return: [
      {
        message: "thank you",
        posterId: 8,
        firstname: "Kaitlan",
        lastname: "Braun",
        image: "8.jpg",
        date: dayjs(new Date(2021, 10, 11, 9, 30)),
      },
    ],
    rating: 4.6,
    date: dayjs(new Date(2021, 10, 10, 10, 12)),
  },
  {
    id: 11,
    postId: 2,
    type: "travel",
    message: "Great communication and very helpful",
    posterId: 3,
    firstname: "Shaunna",
    lastname: "Richard",
    image: "3.jpg",
    return: [],
    rating: 4,
    date: dayjs(new Date(2021, 10, 8, 8, 12)),
  },
  {
    id: 12,
    postId: 3,
    type: "travel",
    message: "Loved this car. And Tony made the whole process a breeze!",
    posterId: 4,
    firstname: "Mandeep",
    lastname: "Mccray",
    image: "4.jpg",
    return: [],
    rating: 4.6,
    date: dayjs(new Date(2021, 9, 30, 10, 35)),
  },
];

module.exports = Review;
