const rightTreatment = [
  {
    type: 1201,
    userId: 1,
    right: [
      {
        category: 1,
        type: 1,
        rightUser: 2,
        description: "ค่ารักษาแบบไม่ค้างคืน",
        cover: 1500,
        unitCover: "บาท/ครั้ง",
        period: 30,
        unitPeriod: "ครั้ง",
        countMethod: "time",
      },
      {
        category: 2,
        type: 1,
        rightUser: 2,
        description: "ค่ารักษาแบบค้างคืน",
        cover: 3000000,
        unitCover: "บาท/ครั้ง",
        period: 3000000,
        unitPeriod: "บาท/ปี",
        countMethod: "cost",
      },
      {
        category: 2,
        type: 2,
        rightUser: 2,
        description: "ค่าห้อง + อาหาร",
        cover: 3000,
        unitCover: "บาท/วัน",
        period: 15000,
        unitPeriod: "บาท/ปี",
        countMethod: "cost",
      },
      {
        category: 2,
        type: 3,
        rightUser: 2,
        description: "ค่าห้อง ICU",
        cover: 6000,
        unitCover: "บาท/วัน",
        period: 60000,
        unitPeriod: "บาท/ปี",
        countMethod: "cost",
      },
      {
        category: 2,
        type: 4,
        rightUser: 2,
        description: "ค่าบำบัดโรค",
        cover: "เบิกจ่ายตามจริง",
        unitCover: "-",
        period: 70000,
        unitPeriod: "บาท/ปี",
        countMethod: "cost",
      },
      {
        category: 2,
        type: 5,
        rightUser: 2,
        description: "ค่าศัลยกรรม",
        cover: "เบิกจ่ายตามจริง",
        unitCover: "-",
        period: 100000,
        unitPeriod: "บาท/ปี",
        countMethod: "cost",
      },
      {
        category: 3,
        type: 1,
        rightUser: 2,
        description: "ค่ารักษาทันตกรรม",
        cover: 5000,
        unitCover: "บาท/ครั้ง",
        period: 15,
        unitPeriod: "ครั้ง",
        countMethod: "time",
      },
      {
        category: 1,
        type: 1,
        rightUser: 1,
        description: "ค่ารักษาแบบไม่ค้างคืน",
        cover: 1500,
        unitCover: "บาท/ครั้ง",
        period: 30,
        unitPeriod: "ครั้ง",
        countMethod: "time",
      },
      {
        category: 2,
        type: 1,
        rightUser: 1,
        description: "ค่ารักษาแบบค้างคืน",
        cover: 2000000,
        unitCover: "บาท/ครั้ง",
        period: 2000000,
        unitPeriod: "บาท/ปี",
        countMethod: "cost",
      },
      {
        category: 2,
        type: 2,
        rightUser: 1,
        description: "ค่าห้อง + อาหาร",
        cover: 2500,
        unitCover: "บาท/วัน",
        period: 10000,
        unitPeriod: "บาท/ปี",
        countMethod: "cost",
      },
      {
        category: 2,
        type: 3,
        rightUser: 1,
        description: "ค่าห้อง ICU",
        cover: 5000,
        unitCover: "บาท/วัน",
        period: 50000,
        unitPeriod: "บาท/ปี",
        countMethod: "cost",
      },
      {
        category: 2,
        type: 4,
        rightUser: 1,
        description: "ค่าบำบัดโรค",
        cover: "เบิกจ่ายตามจริง",
        unitCover: "-",
        period: 50000,
        unitPeriod: "บาท/ปี",
        countMethod: "cost",
      },
      {
        category: 2,
        type: 5,
        rightUser: 1,
        description: "ค่าศัลยกรรม",
        cover: "เบิกจ่ายตามจริง",
        unitCover: "-",
        period: 80000,
        unitPeriod: "บาท/ปี",
        countMethod: "cost",
      },
      {
        category: 3,
        type: 1,
        rightUser: 1,
        description: "ค่ารักษาทันตกรรม",
        cover: 8000,
        unitCover: "บาท/ครั้ง",
        period: 20,
        unitPeriod: "ครั้ง",
        countMethod: "time",
      },
    ],
  },
];

module.exports = rightTreatment;
