export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const USERS_FETCHING = "USERS_FETCHING";
export const USERS_FAILED = "USERS_FAILED";
export const USERS_SUCCESS = "USERS_SUCCESS";

export const USERPROFILE_FETCHING = "USERPROFILE_FETCHING";
export const USERPROFILE_FAILED = "USERPROFILE_FAILED";
export const USERPROFILE_SUCCESS = "USERPROFILE_SUCCESS";

export const WORK_FETCHING = "WORK_FETCHING";
export const WORK_FAILED = "WORK_FAILED";
export const WORK_SUCCESS = "WORK_SUCCESS";

export const TEMPORARY_FETCHING = "TEMPORARY_FETCHING";
export const TEMPORARY_FAILED = "TEMPORARY_FAILED";
export const TEMPORARY_SUCCESS = "TEMPORARY_SUCCESS";

export const COMPANYSINGUP_FETCHING = "COMPANYSINGUP_FETCHING";
export const COMPANYSINGUP_FAILED = "COMPANYSINGUP_FAILED";
export const COMPANYSINGUP_SUCCESS = "COMPANYSINGUP_SUCCESS";

export const COMPANY_MANAGE_FETCHING = "COMPANY_MANAGE_FETCHING";
export const COMPANY_MANAGE_FAILED = "COMPANY_MANAGE_FAILED";
export const COMPANY_MANAGE_SUCCESS = "COMPANY_MANAGE_SUCCESS";

export const COMPANYS_FETCHING = "COMPANYS_FETCHING";
export const COMPANYS_FAILED = "COMPANYS_FAILED";
export const COMPANYS_SUCCESS = "COMPANYS_SUCCESS";

export const BANK_FETCHING = "BANK_FETCHING";
export const BANK_FAILED = "BANK_FAILED";
export const BANK_SUCCESS = "BANK_SUCCESS";

export const BUSINESS_GROUPS_FETCHING = "BUSINESS_GROUPS_FETCHING";
export const BUSINESS_GROUPS_FAILED = "BUSINESS_GROUPS_FAILED";
export const BUSINESS_GROUPS_SUCCESS = "BUSINESS_GROUPS_SUCCESS";
